# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'title.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(464, 272)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainWindowTitleHorizontalLayout = QtWidgets.QHBoxLayout()
        self.mainWindowTitleHorizontalLayout.setObjectName("mainWindowTitleHorizontalLayout")
        self.flameIcon1 = QtWidgets.QLabel(self.centralwidget)
        self.flameIcon1.setMaximumSize(QtCore.QSize(100, 100))
        self.flameIcon1.setText("")
        self.flameIcon1.setPixmap(QtGui.QPixmap("static/fire.png"))
        self.flameIcon1.setScaledContents(True)
        self.flameIcon1.setObjectName("flameIcon1")
        self.mainWindowTitleHorizontalLayout.addWidget(self.flameIcon1, 0, QtCore.Qt.AlignHCenter)
        self.mainWindowTitle = QtWidgets.QLabel(self.centralwidget)
        self.mainWindowTitle.setMaximumSize(QtCore.QSize(16777215, 75))
        self.mainWindowTitle.setStyleSheet("font: 33pt \".AppleSystemUIFont\";")
        self.mainWindowTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.mainWindowTitle.setObjectName("mainWindowTitle")
        self.mainWindowTitleHorizontalLayout.addWidget(self.mainWindowTitle)
        self.flameIcon2 = QtWidgets.QLabel(self.centralwidget)
        self.flameIcon2.setMaximumSize(QtCore.QSize(100, 100))
        self.flameIcon2.setText("")
        self.flameIcon2.setPixmap(QtGui.QPixmap("static/fire.png"))
        self.flameIcon2.setScaledContents(True)
        self.flameIcon2.setObjectName("flameIcon2")
        self.mainWindowTitleHorizontalLayout.addWidget(self.flameIcon2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.mainWindowTitleHorizontalLayout)
        self.mainWindowHorizontalButtonLayout = QtWidgets.QHBoxLayout()
        self.mainWindowHorizontalButtonLayout.setObjectName("mainWindowHorizontalButtonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mainWindowHorizontalButtonLayout.addItem(spacerItem)
        self.mainWindowVerticalButtonLayout = QtWidgets.QVBoxLayout()
        self.mainWindowVerticalButtonLayout.setObjectName("mainWindowVerticalButtonLayout")
        self.openEncounterButton = QtWidgets.QPushButton(self.centralwidget)
        self.openEncounterButton.setMinimumSize(QtCore.QSize(200, 0))
        self.openEncounterButton.setMaximumSize(QtCore.QSize(200, 50))
        self.openEncounterButton.setCheckable(False)
        self.openEncounterButton.setDefault(False)
        self.openEncounterButton.setFlat(False)
        self.openEncounterButton.setObjectName("openEncounterButton")
        self.mainWindowVerticalButtonLayout.addWidget(self.openEncounterButton)
        self.openPartyManagerButton = QtWidgets.QPushButton(self.centralwidget)
        self.openPartyManagerButton.setMinimumSize(QtCore.QSize(200, 0))
        self.openPartyManagerButton.setMaximumSize(QtCore.QSize(200, 50))
        self.openPartyManagerButton.setObjectName("openPartyManagerButton")
        self.mainWindowVerticalButtonLayout.addWidget(self.openPartyManagerButton)
        self.openPCListButton = QtWidgets.QPushButton(self.centralwidget)
        self.openPCListButton.setMinimumSize(QtCore.QSize(200, 0))
        self.openPCListButton.setMaximumSize(QtCore.QSize(200, 50))
        self.openPCListButton.setObjectName("openPCListButton")
        self.mainWindowVerticalButtonLayout.addWidget(self.openPCListButton)
        self.openNPCListButton = QtWidgets.QPushButton(self.centralwidget)
        self.openNPCListButton.setMinimumSize(QtCore.QSize(200, 0))
        self.openNPCListButton.setMaximumSize(QtCore.QSize(200, 50))
        self.openNPCListButton.setObjectName("openNPCListButton")
        self.mainWindowVerticalButtonLayout.addWidget(self.openNPCListButton)
        self.openSpellListPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.openSpellListPushButton.setObjectName("openSpellListPushButton")
        self.mainWindowVerticalButtonLayout.addWidget(self.openSpellListPushButton)
        self.mainWindowHorizontalButtonLayout.addLayout(self.mainWindowVerticalButtonLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mainWindowHorizontalButtonLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.mainWindowHorizontalButtonLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.openEncounterButton.clicked.connect(MainWindow.openEncounter)
        self.openPartyManagerButton.clicked.connect(MainWindow.openPartyManager)
        self.openPCListButton.clicked.connect(MainWindow.openPCList)
        self.openNPCListButton.clicked.connect(MainWindow.openNPCList)
        self.openSpellListPushButton.clicked.connect(MainWindow.openSpellLibrary)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "D&D Automator"))
        self.mainWindowTitle.setText(_translate("MainWindow", "D&D Automator"))
        self.openEncounterButton.setText(_translate("MainWindow", "Open Encounter"))
        self.openPartyManagerButton.setText(_translate("MainWindow", "Manage Party"))
        self.openPCListButton.setText(_translate("MainWindow", "PC List"))
        self.openNPCListButton.setText(_translate("MainWindow", "NPC List"))
        self.openSpellListPushButton.setText(_translate("MainWindow", "Spell List"))
